import {
  ArchiveArrowUpIcon,
  ArchiveIcon,
  ArrowDataTransferVerticalIcon,
  CloudDownloadIcon,
  CloudUploadIcon,
  Download04Icon,
  FileViewIcon,
  GitCommitIcon,
  GitCompareIcon,
  GitPullRequestIcon,
  HierarchyFilesIcon,
  ListViewIcon,
  MinusSignCircleIcon,
  Undo02Icon,
} from "@hugeicons/core-free-icons";
import type { ProductIconMap, SourceControlIconId } from "@/types/ProductIconMappingTypes.ts";

export const sourceControlIcons: ProductIconMap<SourceControlIconId> = {
  discard: Undo02Icon,
  remove: MinusSignCircleIcon,
  "go-to-file": FileViewIcon,
  "git-commit": GitCommitIcon,
  "git-fetch": Download04Icon,
  "repo-push": CloudUploadIcon,
  "repo-pull": CloudDownloadIcon,
  "repo-sync": ArrowDataTransferVerticalIcon,
  sync: ArrowDataTransferVerticalIcon,
  "cloud-upload": CloudUploadIcon,
  "cloud-download": CloudDownloadIcon,
  "git-stash": ArchiveIcon,
  "git-stash-apply": ArchiveArrowUpIcon,
  "git-stash-pop": ArchiveArrowUpIcon,
  "git-pull-request": GitPullRequestIcon,
  "diff-multiple": GitCompareIcon,
  "compare-changes": GitCompareIcon,
  "list-tree": HierarchyFilesIcon,
  "list-flat": ListViewIcon,
};
