import {
  CancelCircleIcon,
  Copy01Icon,
  FileAddIcon,
  FilterIcon,
  FolderAddIcon,
  GitBranchIcon,
  LayoutTwoColumnIcon,
  LinkSquare02Icon,
  LockIcon,
  MoreHorizontalCircle01Icon,
  MoreVerticalIcon,
  PencilEdit02Icon,
  PinIcon,
  PlusSignCircleIcon,
  RefreshIcon,
  Search01Icon,
  SearchAddIcon,
  Settings04Icon,
  UnfoldLessIcon,
  UnfoldMoreIcon,
  ViewIcon,
  ViewOffSlashIcon,
} from "@hugeicons/core-free-icons";
import type { ProductIconMap, WorkbenchActionIconId } from "@/types/ProductIconMappingTypes.ts";

export const workbenchActionIcons: ProductIconMap<WorkbenchActionIconId> = {
  close: CancelCircleIcon,
  "close-compact": CancelCircleIcon,
  "close-small": CancelCircleIcon,
  "close-all": CancelCircleIcon,
  "clear-all": CancelCircleIcon,
  trash: CancelCircleIcon,
  trashcan: CancelCircleIcon,
  gear: Settings04Icon,
  "gear-compact": Settings04Icon,
  "settings-gear": Settings04Icon,
  settings: Settings04Icon,
  "settings-compact": Settings04Icon,
  search: Search01Icon,
  "search-compact": Search01Icon,
  "search-new-editor": SearchAddIcon,
  add: PlusSignCircleIcon,
  "add-compact": PlusSignCircleIcon,
  "add-small": PlusSignCircleIcon,
  plus: PlusSignCircleIcon,
  ellipsis: MoreHorizontalCircle01Icon,
  more: MoreHorizontalCircle01Icon,
  "kebab-horizontal": MoreHorizontalCircle01Icon,
  "kebab-vertical": MoreVerticalIcon,
  refresh: RefreshIcon,
  "refresh-compact": RefreshIcon,
  filter: FilterIcon,
  "list-filter": FilterIcon,
  "new-file": FileAddIcon,
  "new-folder": FolderAddIcon,
  "collapse-all": UnfoldLessIcon,
  "collapse-all-compact": UnfoldLessIcon,
  "expand-all": UnfoldMoreIcon,
  copy: Copy01Icon,
  edit: PencilEdit02Icon,
  "edit-compact": PencilEdit02Icon,
  pin: PinIcon,
  pinned: PinIcon,
  "link-external": LinkSquare02Icon,
  eye: ViewIcon,
  "eye-closed": ViewOffSlashIcon,
  lock: LockIcon,
  "lock-small": LockIcon,
  "git-branch": GitBranchIcon,
  "git-branch-compact": GitBranchIcon,
  "split-horizontal": LayoutTwoColumnIcon,
};
